version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - redis

  redis:
    image: "redis:3.2.0-alpine"
    ports:
      - "6379:6379"