version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - redis

  redis:
    image: "redis:3.2.0-alpine"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"